spring.application.name=user-service
eureka.client.serviceUrl.defaultZone=http://localhost:8760/eureka/
server.port=8091
eureka.instance.hostname=localhost

logging.file.name=logs/onepiece.log
spring.datasource.url=jdbc:mysql://localhost:3306/onepiece
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# gsqFgOqhOTREiwdzIY1ck2ABHDhdFddMrgFGV3UOd+o=
# To generate a new secret key use the command:
# openssl rand -base64 32
spring.jwt.secret=${JWT_AUTH_KEY}
spring.jwt.expiration=86400000

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.defer-datasource-initialization=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.genc=TRACE